// AUDIO PATCH CONNECTIONS, GENERATED BY TEENSY AUDIO DESIGN TOOL
// GUI GENERATED CODE CAN BE IMPORTED INTO TEENSY AUDIO DESIGN TOOL AND EDITED IF NECESSARY
// https://www.pjrc.com/teensy/gui/

#ifndef Audio_Connections_h
#define Audio_Connections_h

// GUItool: begin automatically generated code
AudioSynthNoiseWhite     V8_N;           //xy=121.00390625,1267.9999987483025
AudioSynthWaveform       V6_B;           //xy=123.00390625,943.9999987483025
AudioSynthWaveform       V6_A;           //xy=124.00390625,902.9999987483025
AudioSynthNoiseWhite     V7_N;           //xy=124.00390625,1127.9999987483025
AudioSynthWaveform       V8_B;           //xy=124.00390625,1224.9999987483025
AudioSynthNoiseWhite     V6_N;           //xy=125.00390625,985.9999987483025
AudioSynthWaveform       V7_A;           //xy=125.00390625,1046.9999987483025
AudioSynthWaveform       V7_B;           //xy=126.00390625,1088.9999987483025
AudioSynthWaveform       V8_A;           //xy=126.00390625,1182.9999987483025
AudioSynthWaveform       V5_B;           //xy=129.00390625,801.9999987483025
AudioSynthWaveform       V3_A;           //xy=131.00390625,473.99999874830246
AudioSynthWaveform       V5_A;           //xy=131.00390625,761.9999987483025
AudioSynthNoiseWhite     V2_N;           //xy=133.00390625,426.99999874830246
AudioSynthWaveform       V3_B;           //xy=133.00390625,523.9999987483025
AudioSynthNoiseWhite     V3_N;           //xy=133.00390625,567.9999987483025
AudioSynthWaveform       V2_B;           //xy=134.00390625,378.99999874830246
AudioSynthNoiseWhite     V1_N;           //xy=135.00390625,282.99999874830246
AudioSynthWaveform       V4_A;           //xy=134.00390625,616.9999987483025
AudioSynthWaveform       V4_B;           //xy=134.00390625,658.9999987483025
AudioSynthWaveform       V2_A;           //xy=136.00390625,330.99999874830246
AudioSynthNoiseWhite     V5_N;           //xy=134.00390625,845.9999987483025
AudioSynthWaveform       V1_B;           //xy=139.00390625,243.99999874830246
AudioSynthNoiseWhite     V4_N;           //xy=140.00390625,697.9999987483025
AudioSynthWaveform       V1_A;           //xy=143.00390625,203.99999874830246
AudioSynthWaveformDc     DC_OFFSET;      //xy=227.00390625,138.99999874830246
AudioMixer4              V3_MIX;         //xy=288.00390625,506.99999874830246
AudioMixer4              V8_MIX;         //xy=290.00390625,1224.9999987483025
AudioMixer4              V5_MIX;         //xy=295.00390625,793.9999987483025
AudioMixer4              V7_MIX;         //xy=294.00390625,1081.9999987483025
AudioMixer4              V6_MIX;         //xy=296.00390625,930.9999987483025
AudioMixer4              V4_MIX;         //xy=300.00390625,630.9999987483025
AudioMixer4              V1_MIX;         //xy=305.00390625,246.99999874830246
AudioMixer4              V2_MIX;         //xy=309.00390625,367.99999874830246
AudioSynthWaveformSine   LFO;            //xy=351.00390625,92.99999874830246
AudioEffectEnvelope      V7_FILT_ENV;    //xy=439.00390625,1051.9999987483025
AudioEffectEnvelope      V6_FILT_ENV;    //xy=445.00390625,909.9999987483025
AudioEffectEnvelope      V8_FILT_ENV;    //xy=445.00390625,1202.9999987483025
AudioAmplifier           V8_AMP;         //xy=446.00390625,1250.9999987483025
AudioAmplifier           V5_AMP;         //xy=454.00390625,805.9999987483025
AudioAmplifier           V7_AMP;         //xy=453.00390625,1088.9999987483025
AudioEffectEnvelope      V3_FILT_ENV;    //xy=458.00390625,489.99999874830246
AudioEffectEnvelope      V5_FILT_ENV;    //xy=459.00390625,760.9999987483025
AudioAmplifier           V6_AMP;         //xy=460.00390625,949.9999987483025
AudioAmplifier           V2_AMP;         //xy=465.00390625,411.99999874830246
AudioAmplifier           V4_AMP;         //xy=465.00390625,662.9999987483025
AudioEffectEnvelope      V4_FILT_ENV;    //xy=466.00390625,621.9999987483025
AudioAmplifier           V3_AMP;         //xy=468.00390625,536.9999987483025
AudioAmplifier           V1_AMP;         //xy=477.00390625,239.99999874830246
AudioEffectEnvelope      V2_FILT_ENV;    //xy=481.00390625,353.99999874830246
AudioEffectEnvelope      V1_FILT_ENV;    //xy=484.00390625,295.99999874830246
AudioMixer4              LFO_MIXER_AMP;  //xy=507.00390625,180.99999874830246
AudioEffectMultiply      MULT_7;         //xy=613.00390625,1061.9999987483025
AudioEffectMultiply      MULT_8;         //xy=615.00390625,1200.9999987483025
AudioEffectMultiply      MULT_3;         //xy=631.00390625,483.99999874830246
AudioEffectMultiply      MULT_6;         //xy=632.00390625,909.9999987483025
AudioEffectMultiply      MULT_5;         //xy=638.00390625,777.9999987483025
AudioEffectMultiply      MULT_1;         //xy=642.00390625,234.99999874830246
AudioEffectMultiply      MULT_4;         //xy=642.00390625,610.9999987483025
AudioEffectMultiply      MULT_2;         //xy=648.00390625,352.99999874830246
AudioFilterStateVariable V7_FILT;        //xy=770.00390625,1097.9999987483025
AudioFilterStateVariable V3_FILT;        //xy=773.00390625,523.9999987483025
AudioFilterStateVariable V2_FILT;        //xy=775.00390625,409.99999874830246
AudioFilterStateVariable V6_FILT;        //xy=774.00390625,948.9999987483025
AudioFilterStateVariable V8_FILT;        //xy=774.00390625,1233.9999987483025
AudioFilterStateVariable V1_FILT;        //xy=797.00390625,297.99999874830246
AudioFilterStateVariable V4_FILT;        //xy=796.00390625,642.9999987483025
AudioFilterStateVariable V5_FILT;        //xy=798.00390625,796.9999987483025
AudioEffectEnvelope      V1_ENV;         //xy=960.00390625,313.99999874830246
AudioEffectEnvelope      V2_ENV;         //xy=967.00390625,400.99999874830246
AudioEffectEnvelope      V6_ENV;         //xy=976.00390625,892.9999987483025
AudioEffectEnvelope      V7_ENV;         //xy=979.00390625,955.9999987483025
AudioEffectEnvelope      V3_ENV;         //xy=982.00390625,524.9999987483025
AudioEffectEnvelope      V5_ENV;         //xy=990.00390625,805.9999987483025
AudioEffectEnvelope      V4_ENV;         //xy=994.00390625,649.9999987483025
AudioEffectEnvelope      V8_ENV;         //xy=995.00390625,1097.9999987483025
AudioMixer4              V14_MIX;        //xy=1292.00390625,662.9999987483025
AudioMixer4              V58_MIX;        //xy=1293.00390625,732.9999987483025
AudioMixer4              ALL_VOICE_MIX;  //xy=1513.00390625,748.9999987483025
AudioAmplifier           amp1;           //xy=1678.00390625,744.9999987483025
AudioAnalyzePeak         peak1;          //xy=1811.00390625,574.00390625
AudioOutputI2S           i2s1;           //xy=1823.00390625,744.9999987483025
AudioConnection          patchCord1(V8_N, 0, V8_MIX, 2);
AudioConnection          patchCord2(V6_B, 0, V6_MIX, 1);
AudioConnection          patchCord3(V6_A, 0, V6_MIX, 0);
AudioConnection          patchCord4(V7_N, 0, V7_MIX, 2);
AudioConnection          patchCord5(V8_B, 0, V8_MIX, 1);
AudioConnection          patchCord6(V6_N, 0, V6_MIX, 2);
AudioConnection          patchCord7(V7_A, 0, V7_MIX, 0);
AudioConnection          patchCord8(V7_B, 0, V7_MIX, 1);
AudioConnection          patchCord9(V8_A, 0, V8_MIX, 0);
AudioConnection          patchCord10(V5_B, 0, V5_MIX, 1);
AudioConnection          patchCord11(V3_A, 0, V3_MIX, 0);
AudioConnection          patchCord12(V5_A, 0, V5_MIX, 0);
AudioConnection          patchCord13(V2_N, 0, V2_MIX, 2);
AudioConnection          patchCord14(V3_B, 0, V3_MIX, 1);
AudioConnection          patchCord15(V3_N, 0, V3_MIX, 2);
AudioConnection          patchCord16(V2_B, 0, V2_MIX, 1);
AudioConnection          patchCord17(V1_N, 0, V1_MIX, 2);
AudioConnection          patchCord18(V4_A, 0, V4_MIX, 0);
AudioConnection          patchCord19(V4_B, 0, V4_MIX, 1);
AudioConnection          patchCord20(V2_A, 0, V2_MIX, 0);
AudioConnection          patchCord21(V5_N, 0, V5_MIX, 2);
AudioConnection          patchCord22(V1_B, 0, V1_MIX, 1);
AudioConnection          patchCord23(V4_N, 0, V4_MIX, 2);
AudioConnection          patchCord24(V1_A, 0, V1_MIX, 0);
AudioConnection          patchCord25(DC_OFFSET, V1_FILT_ENV);
AudioConnection          patchCord26(DC_OFFSET, V2_FILT_ENV);
AudioConnection          patchCord27(DC_OFFSET, V3_FILT_ENV);
AudioConnection          patchCord28(DC_OFFSET, V4_FILT_ENV);
AudioConnection          patchCord29(DC_OFFSET, V5_FILT_ENV);
AudioConnection          patchCord30(DC_OFFSET, V6_FILT_ENV);
AudioConnection          patchCord31(DC_OFFSET, V7_FILT_ENV);
AudioConnection          patchCord32(DC_OFFSET, V8_FILT_ENV);
AudioConnection          patchCord33(DC_OFFSET, 0, LFO_MIXER_AMP, 0);
AudioConnection          patchCord34(V3_MIX, V3_AMP);
AudioConnection          patchCord35(V8_MIX, V8_AMP);
AudioConnection          patchCord36(V5_MIX, V5_AMP);
AudioConnection          patchCord37(V7_MIX, V7_AMP);
AudioConnection          patchCord38(V6_MIX, V6_AMP);
AudioConnection          patchCord39(V4_MIX, V4_AMP);
AudioConnection          patchCord40(V1_MIX, V1_AMP);
AudioConnection          patchCord41(V2_MIX, V2_AMP);
AudioConnection          patchCord42(LFO, 0, LFO_MIXER_AMP, 1);
AudioConnection          patchCord43(V7_FILT_ENV, 0, MULT_7, 1);
AudioConnection          patchCord44(V6_FILT_ENV, 0, MULT_6, 1);
AudioConnection          patchCord45(V8_FILT_ENV, 0, MULT_8, 1);
AudioConnection          patchCord46(V8_AMP, 0, V8_FILT, 0);
AudioConnection          patchCord47(V5_AMP, 0, V5_FILT, 0);
AudioConnection          patchCord48(V7_AMP, 0, V7_FILT, 0);
AudioConnection          patchCord49(V3_FILT_ENV, 0, MULT_3, 1);
AudioConnection          patchCord50(V5_FILT_ENV, 0, MULT_5, 1);
AudioConnection          patchCord51(V6_AMP, 0, V6_FILT, 0);
AudioConnection          patchCord52(V2_AMP, 0, V2_FILT, 0);
AudioConnection          patchCord53(V4_AMP, 0, V4_FILT, 0);
AudioConnection          patchCord54(V4_FILT_ENV, 0, MULT_4, 1);
AudioConnection          patchCord55(V3_AMP, 0, V3_FILT, 0);
AudioConnection          patchCord56(V1_AMP, 0, V1_FILT, 0);
AudioConnection          patchCord57(V2_FILT_ENV, 0, MULT_2, 1);
AudioConnection          patchCord58(V1_FILT_ENV, 0, MULT_1, 1);
AudioConnection          patchCord59(LFO_MIXER_AMP, 0, MULT_1, 0);
AudioConnection          patchCord60(LFO_MIXER_AMP, 0, MULT_2, 0);
AudioConnection          patchCord61(LFO_MIXER_AMP, 0, MULT_3, 0);
AudioConnection          patchCord62(LFO_MIXER_AMP, 0, MULT_4, 0);
AudioConnection          patchCord63(LFO_MIXER_AMP, 0, MULT_5, 0);
AudioConnection          patchCord64(LFO_MIXER_AMP, 0, MULT_6, 0);
AudioConnection          patchCord65(LFO_MIXER_AMP, 0, MULT_7, 0);
AudioConnection          patchCord66(LFO_MIXER_AMP, 0, MULT_8, 0);
AudioConnection          patchCord67(MULT_7, 0, V7_FILT, 1);
AudioConnection          patchCord68(MULT_8, 0, V8_FILT, 1);
AudioConnection          patchCord69(MULT_3, 0, V3_FILT, 1);
AudioConnection          patchCord70(MULT_6, 0, V6_FILT, 1);
AudioConnection          patchCord71(MULT_5, 0, V5_FILT, 1);
AudioConnection          patchCord72(MULT_1, 0, V1_FILT, 1);
AudioConnection          patchCord73(MULT_4, 0, V4_FILT, 1);
AudioConnection          patchCord74(MULT_2, 0, V2_FILT, 1);
AudioConnection          patchCord75(V7_FILT, 0, V7_ENV, 0);
AudioConnection          patchCord76(V3_FILT, 0, V3_ENV, 0);
AudioConnection          patchCord77(V2_FILT, 0, V2_ENV, 0);
AudioConnection          patchCord78(V6_FILT, 0, V6_ENV, 0);
AudioConnection          patchCord79(V8_FILT, 0, V8_ENV, 0);
AudioConnection          patchCord80(V1_FILT, 0, V1_ENV, 0);
AudioConnection          patchCord81(V4_FILT, 0, V4_ENV, 0);
AudioConnection          patchCord82(V5_FILT, 0, V5_ENV, 0);
AudioConnection          patchCord83(V1_ENV, 0, V14_MIX, 0);
AudioConnection          patchCord84(V2_ENV, 0, V14_MIX, 1);
AudioConnection          patchCord85(V6_ENV, 0, V58_MIX, 1);
AudioConnection          patchCord86(V7_ENV, 0, V58_MIX, 2);
AudioConnection          patchCord87(V3_ENV, 0, V14_MIX, 2);
AudioConnection          patchCord88(V5_ENV, 0, V58_MIX, 0);
AudioConnection          patchCord89(V4_ENV, 0, V14_MIX, 3);
AudioConnection          patchCord90(V8_ENV, 0, V58_MIX, 3);
AudioConnection          patchCord91(V14_MIX, 0, ALL_VOICE_MIX, 0);
AudioConnection          patchCord92(V58_MIX, 0, ALL_VOICE_MIX, 1);
AudioConnection          patchCord93(ALL_VOICE_MIX, amp1);
AudioConnection          patchCord94(amp1, 0, i2s1, 0);
AudioConnection          patchCord95(amp1, 0, i2s1, 1);
AudioConnection          patchCord96(amp1, peak1);
AudioControlSGTL5000     sgtl5000_1;     //xy=1390.00390625,919.9999987483025
// GUItool: end automatically generated code



#endif