// AUDIO PATCH CONNECTIONS, GENERATED BY TEENSY AUDIO DESIGN TOOL
// GUI GENERATED CODE CAN BE IMPORTED INTO TEENSY AUDIO DESIGN TOOL AND EDITED IF NECESSARY
// https://www.pjrc.com/teensy/gui/

#ifndef Audio_Connections_h
#define Audio_Connections_h

// GUItool: begin automatically generated code
AudioSynthWaveform       V9_A;           //xy=110.00390625,1293.9999985694885
AudioSynthWaveform       V9_B;           //xy=115.00390625,1330.9999985694885
AudioSynthNoiseWhite      V9_N;           //xy=116.00390625,1371.9999985694885
AudioSynthWaveform       V10_A;          //xy=118.00390625,1446.9999985694885
AudioSynthWaveform       V10_B;          //xy=119.00390625,1484.9999985694885
AudioSynthNoiseWhite      V10_N;          //xy=119.00390625,1529.9999985694885
AudioSynthNoiseWhite      V12_N;          //xy=118.00390625,1811.9999985694885
AudioSynthWaveform       V11_A;          //xy=119.00390625,1589.9999985694885
AudioSynthWaveform       V11_B;          //xy=119.00390625,1624.9999985694885
AudioSynthNoiseWhite      V8_N;           //xy=121.00390625,1221.9999985694885
AudioSynthWaveform       V6_B;           //xy=123.00390625,897.9999985694885
AudioSynthWaveform       V12_B;          //xy=120.00390625,1769.9999985694885
AudioSynthWaveform       V6_A;           //xy=124.00390625,856.9999985694885
AudioSynthNoiseWhite      V11_N;          //xy=121.00390625,1664.9999985694885
AudioSynthNoiseWhite      V7_N;           //xy=124.00390625,1081.9999985694885
AudioSynthWaveform       V8_B;           //xy=124.00390625,1178.9999985694885
AudioSynthNoiseWhite      V6_N;           //xy=125.00390625,939.9999985694885
AudioSynthWaveform       V7_A;           //xy=125.00390625,1000.9999985694885
AudioSynthWaveform       V12_A;          //xy=123.00390625,1730.9999985694885
AudioSynthWaveform       V7_B;           //xy=126.00390625,1042.9999985694885
AudioSynthWaveform       V8_A;           //xy=126.00390625,1136.9999985694885
AudioSynthWaveform       V5_B;           //xy=129.00390625,755.9999985694885
AudioSynthWaveform       V3_A;           //xy=131.00390625,427.9999985694885
AudioSynthWaveform       V5_A;           //xy=131.00390625,715.9999985694885
AudioSynthNoiseWhite      V2_N;           //xy=133.00390625,380.9999985694885
AudioSynthWaveform       V3_B;           //xy=133.00390625,477.9999985694885
AudioSynthNoiseWhite      V3_N;           //xy=133.00390625,521.9999985694885
AudioSynthWaveform       V2_B;           //xy=134.00390625,332.9999985694885
AudioSynthNoiseWhite      V1_N;           //xy=135.00390625,236.99999856948853
AudioSynthWaveform       V4_A;           //xy=134.00390625,570.9999985694885
AudioSynthWaveform       V4_B;           //xy=134.00390625,612.9999985694885
AudioSynthWaveform       V2_A;           //xy=136.00390625,284.9999985694885
AudioSynthNoiseWhite      V5_N;           //xy=134.00390625,799.9999985694885
AudioSynthWaveform       V1_B;           //xy=139.00390625,197.99999856948853
AudioSynthNoiseWhite      V4_N;           //xy=140.00390625,651.9999985694885
AudioSynthWaveform       V1_A;           //xy=143.00390625,157.99999856948853
AudioSynthWaveformDc     DC_OFFSET;      //xy=227.00390625,92.99999856948853
AudioMixer4              V10_MIX;        //xy=267.00390625,1499.9999985694885
AudioMixer4              V11_MIX;        //xy=272.00390625,1636.9999985694885
AudioMixer4              V3_MIX;         //xy=288.00390625,460.9999985694885
AudioMixer4              V8_MIX;         //xy=290.00390625,1178.9999985694885
AudioMixer4              V5_MIX;         //xy=295.00390625,747.9999985694885
AudioMixer4              V7_MIX;         //xy=294.00390625,1035.9999985694885
AudioMixer4              V9_MIX;         //xy=294.00390625,1322.9999985694885
AudioMixer4              V6_MIX;         //xy=296.00390625,884.9999985694885
AudioMixer4              V4_MIX;         //xy=300.00390625,584.9999985694885
AudioMixer4              V1_MIX;         //xy=305.00390625,200.99999856948853
AudioMixer4              V2_MIX;         //xy=309.00390625,321.9999985694885
AudioMixer4              V12_MIX;        //xy=312.00390625,1761.9999985694885
AudioSynthWaveformSine   LFO;            //xy=351.00390625,46.999998569488525
AudioEffectEnvelope      V7_FILT_ENV;    //xy=439.00390625,1005.9999985694885
AudioEffectEnvelope      V6_FILT_ENV;    //xy=445.00390625,863.9999985694885
AudioEffectEnvelope      V8_FILT_ENV;    //xy=445.00390625,1156.9999985694885
AudioAmplifier           V8_AMP;           //xy=446.00390625,1204.25390625
AudioEffectEnvelope      V9_FILT_ENV;    //xy=448.00390625,1306.9999985694885
AudioEffectEnvelope      V11_FILT_ENV;   //xy=449.00390625,1599.9999985694885
AudioEffectEnvelope      V10_FILT_ENV;   //xy=450.00390625,1475.9999985694885
AudioAmplifier           V9_AMP;          //xy=451.00390625,1347.25390625
AudioAmplifier           V5_AMP;           //xy=454.00390625,759.00390625
AudioAmplifier           V10_AMP;          //xy=451.00390625,1522.75390625
AudioAmplifier           V7_AMP;           //xy=453.00390243530273,1042.0039081573486
AudioAmplifier           V11_AMP;          //xy=453.00390625,1640.75390625
AudioEffectEnvelope      V3_FILT_ENV;    //xy=458.00390625,443.9999985694885
AudioEffectEnvelope      V5_FILT_ENV;    //xy=459.00390243530273,714.0000448226929
AudioAmplifier           V6_AMP;           //xy=460.00390243530273,903.0039539337158
AudioAmplifier           V2_AMP;           //xy=465.00390625,365.00390625
AudioAmplifier           V4_AMP;           //xy=465.00390434265137,616.0038976669312
AudioEffectEnvelope      V4_FILT_ENV;    //xy=466.00390625,575.9999985694885
AudioAmplifier           V3_AMP;           //xy=468.00390243530273,490.00389766693115
AudioAmplifier           V1_AMP;           //xy=477.00389862060547,193.00390434265137
AudioEffectEnvelope      V2_FILT_ENV;    //xy=481.00390625,307.9999985694885
AudioEffectEnvelope      V1_FILT_ENV;    //xy=484.00390625,249.00000667572021
AudioAmplifier           V12_AMP;          //xy=479.0038948059082,1779.7539167404175
AudioEffectEnvelope      V12_FILT_ENV;   //xy=486.00390625,1739.9999985694885
AudioMixer4              LFO_MIXER_AMP;  //xy=507.00390625,134.99999856948853
AudioEffectMultiply      MULT_7;         //xy=613.00390625,1015.9999985694885
AudioEffectMultiply      MULT_8;         //xy=615.00390625,1154.9999985694885
AudioEffectMultiply      MULT_9;         //xy=621.00390625,1311.9999985694885
AudioEffectMultiply      MULT_10;        //xy=625.00390625,1480.9999985694885
AudioEffectMultiply      MULT_3;         //xy=631.00390625,437.9999985694885
AudioEffectMultiply      MULT_6;         //xy=632.00390625,863.9999985694885
AudioEffectMultiply      MULT_11;        //xy=632.00390625,1595.9999985694885
AudioEffectMultiply      MULT_5;         //xy=638.00390625,731.9999985694885
AudioEffectMultiply      MULT_1;         //xy=642.00390625,188.99999856948853
AudioEffectMultiply      MULT_4;         //xy=642.00390625,564.9999985694885
AudioEffectMultiply      MULT_2;         //xy=648.00390625,306.9999985694885
AudioEffectMultiply      MULT_12;        //xy=661.00390625,1742.9999985694885
AudioFilterStateVariable V9_FILT;        //xy=768.00390625,1350.9999985694885
AudioFilterStateVariable V7_FILT;        //xy=770.00390625,1051.9999985694885
AudioFilterStateVariable V3_FILT;        //xy=773.00390625,477.9999985694885
AudioFilterStateVariable V2_FILT;        //xy=775.00390625,363.9999985694885
AudioFilterStateVariable V6_FILT;        //xy=774.00390625,902.9999985694885
AudioFilterStateVariable V8_FILT;        //xy=774.00390625,1187.9999985694885
AudioFilterStateVariable V10_FILT;       //xy=776.00390625,1507.9999985694885
AudioFilterStateVariable V1_FILT;        //xy=797.00390625,251.99999856948853
AudioFilterStateVariable V4_FILT;        //xy=796.00390625,596.9999985694885
AudioFilterStateVariable V5_FILT;        //xy=798.00390625,750.9999985694885
AudioFilterStateVariable V11_FILT;       //xy=809.00390625,1625.9999985694885
AudioFilterStateVariable V12_FILT;       //xy=836.00390625,1775.9999985694885
AudioEffectEnvelope      V1_ENV;         //xy=960.00390625,267.9999985694885
AudioEffectEnvelope      V2_ENV;         //xy=967.00390625,354.9999985694885
AudioEffectEnvelope      V6_ENV;         //xy=976.00390625,846.9999985694885
AudioEffectEnvelope      V7_ENV;         //xy=979.00390625,909.9999985694885
AudioEffectEnvelope      V9_ENV;         //xy=979.00390625,1225.9999985694885
AudioEffectEnvelope      V3_ENV;         //xy=982.00390625,478.9999985694885
AudioEffectEnvelope      V10_ENV;        //xy=984.00390625,1351.9999985694885
AudioEffectEnvelope      V5_ENV;         //xy=990.00390625,759.9999985694885
AudioEffectEnvelope      V4_ENV;         //xy=994.00390625,603.9999985694885
AudioEffectEnvelope      V8_ENV;         //xy=995.00390625,1051.9999985694885
AudioEffectEnvelope      V11_ENV;        //xy=1011.00390625,1568.9999985694885
AudioEffectEnvelope      V12_ENV;        //xy=1027.00390625,1694.9999985694885
AudioMixer4              V14_MIX;        //xy=1292.00390625,616.9999985694885
AudioMixer4              V912_MIX;       //xy=1292.00390625,762.9999985694885
AudioMixer4              V58_MIX;        //xy=1293.00390625,686.9999985694885
AudioMixer4              ALL_VOICE_MIX;  //xy=1513.00390625,702.9999985694885
AudioAmplifier           amp1;           //xy=1678.00390625,698.9999985694885
AudioOutputI2S           i2s1;           //xy=1823.00390625,698.9999985694885
AudioConnection          patchCord1(V9_A, 0, V9_MIX, 0);
AudioConnection          patchCord2(V9_B, 0, V9_MIX, 1);
AudioConnection          patchCord3(V9_N, 0, V9_MIX, 2);
AudioConnection          patchCord4(V10_A, 0, V10_MIX, 0);
AudioConnection          patchCord5(V10_B, 0, V10_MIX, 1);
AudioConnection          patchCord6(V10_N, 0, V10_MIX, 2);
AudioConnection          patchCord7(V12_N, 0, V12_MIX, 2);
AudioConnection          patchCord8(V11_A, 0, V11_MIX, 0);
AudioConnection          patchCord9(V11_B, 0, V11_MIX, 1);
AudioConnection          patchCord10(V8_N, 0, V8_MIX, 2);
AudioConnection          patchCord11(V6_B, 0, V6_MIX, 1);
AudioConnection          patchCord12(V12_B, 0, V12_MIX, 1);
AudioConnection          patchCord13(V6_A, 0, V6_MIX, 0);
AudioConnection          patchCord14(V11_N, 0, V11_MIX, 2);
AudioConnection          patchCord15(V7_N, 0, V7_MIX, 2);
AudioConnection          patchCord16(V8_B, 0, V8_MIX, 1);
AudioConnection          patchCord17(V6_N, 0, V6_MIX, 2);
AudioConnection          patchCord18(V7_A, 0, V7_MIX, 0);
AudioConnection          patchCord19(V12_A, 0, V12_MIX, 0);
AudioConnection          patchCord20(V7_B, 0, V7_MIX, 1);
AudioConnection          patchCord21(V8_A, 0, V8_MIX, 0);
AudioConnection          patchCord22(V5_B, 0, V5_MIX, 1);
AudioConnection          patchCord23(V3_A, 0, V3_MIX, 0);
AudioConnection          patchCord24(V5_A, 0, V5_MIX, 0);
AudioConnection          patchCord25(V2_N, 0, V2_MIX, 2);
AudioConnection          patchCord26(V3_B, 0, V3_MIX, 1);
AudioConnection          patchCord27(V3_N, 0, V3_MIX, 2);
AudioConnection          patchCord28(V2_B, 0, V2_MIX, 1);
AudioConnection          patchCord29(V1_N, 0, V1_MIX, 2);
AudioConnection          patchCord30(V4_A, 0, V4_MIX, 0);
AudioConnection          patchCord31(V4_B, 0, V4_MIX, 1);
AudioConnection          patchCord32(V2_A, 0, V2_MIX, 0);
AudioConnection          patchCord33(V5_N, 0, V5_MIX, 2);
AudioConnection          patchCord34(V1_B, 0, V1_MIX, 1);
AudioConnection          patchCord35(V4_N, 0, V4_MIX, 2);
AudioConnection          patchCord36(V1_A, 0, V1_MIX, 0);
AudioConnection          patchCord37(DC_OFFSET, V1_FILT_ENV);
AudioConnection          patchCord38(DC_OFFSET, V2_FILT_ENV);
AudioConnection          patchCord39(DC_OFFSET, V3_FILT_ENV);
AudioConnection          patchCord40(DC_OFFSET, V4_FILT_ENV);
AudioConnection          patchCord41(DC_OFFSET, V5_FILT_ENV);
AudioConnection          patchCord42(DC_OFFSET, V6_FILT_ENV);
AudioConnection          patchCord43(DC_OFFSET, V7_FILT_ENV);
AudioConnection          patchCord44(DC_OFFSET, V8_FILT_ENV);
AudioConnection          patchCord45(DC_OFFSET, V9_FILT_ENV);
AudioConnection          patchCord46(DC_OFFSET, V10_FILT_ENV);
AudioConnection          patchCord47(DC_OFFSET, V11_FILT_ENV);
AudioConnection          patchCord48(DC_OFFSET, V12_FILT_ENV);
AudioConnection          patchCord49(DC_OFFSET, 0, LFO_MIXER_AMP, 0);
AudioConnection          patchCord50(V10_MIX, V10_AMP);
AudioConnection          patchCord51(V11_MIX, V11_AMP);
AudioConnection          patchCord52(V3_MIX, V3_AMP);
AudioConnection          patchCord53(V8_MIX, V8_AMP);
AudioConnection          patchCord54(V5_MIX, V5_AMP);
AudioConnection          patchCord55(V7_MIX, V7_AMP);
AudioConnection          patchCord56(V9_MIX, V9_AMP);
AudioConnection          patchCord57(V6_MIX, V6_AMP);
AudioConnection          patchCord58(V4_MIX, V4_AMP);
AudioConnection          patchCord59(V1_MIX, V1_AMP);
AudioConnection          patchCord60(V2_MIX, V2_AMP);
AudioConnection          patchCord61(V12_MIX, V12_AMP);
AudioConnection          patchCord62(LFO, 0, LFO_MIXER_AMP, 1);
AudioConnection          patchCord63(V7_FILT_ENV, 0, MULT_7, 1);
AudioConnection          patchCord64(V6_FILT_ENV, 0, MULT_6, 1);
AudioConnection          patchCord65(V8_FILT_ENV, 0, MULT_8, 1);
AudioConnection          patchCord66(V8_AMP, 0, V8_FILT, 0);
AudioConnection          patchCord67(V9_FILT_ENV, 0, MULT_9, 1);
AudioConnection          patchCord68(V11_FILT_ENV, 0, MULT_11, 1);
AudioConnection          patchCord69(V10_FILT_ENV, 0, MULT_10, 1);
AudioConnection          patchCord70(V9_AMP, 0, V9_FILT, 0);
AudioConnection          patchCord71(V5_AMP, 0, V5_FILT, 0);
AudioConnection          patchCord72(V10_AMP, 0, V10_FILT, 0);
AudioConnection          patchCord73(V7_AMP, 0, V7_FILT, 0);
AudioConnection          patchCord74(V11_AMP, 0, V11_FILT, 0);
AudioConnection          patchCord75(V3_FILT_ENV, 0, MULT_3, 1);
AudioConnection          patchCord76(V5_FILT_ENV, 0, MULT_5, 1);
AudioConnection          patchCord77(V6_AMP, 0, V6_FILT, 0);
AudioConnection          patchCord78(V2_AMP, 0, V2_FILT, 0);
AudioConnection          patchCord79(V4_AMP, 0, V4_FILT, 0);
AudioConnection          patchCord80(V4_FILT_ENV, 0, MULT_4, 1);
AudioConnection          patchCord81(V3_AMP, 0, V3_FILT, 0);
AudioConnection          patchCord82(V1_AMP, 0, V1_FILT, 0);
AudioConnection          patchCord83(V2_FILT_ENV, 0, MULT_2, 1);
AudioConnection          patchCord84(V1_FILT_ENV, 0, MULT_1, 1);
AudioConnection          patchCord85(V12_AMP, 0, V12_FILT, 0);
AudioConnection          patchCord86(V12_FILT_ENV, 0, MULT_12, 1);
AudioConnection          patchCord87(LFO_MIXER_AMP, 0, MULT_1, 0);
AudioConnection          patchCord88(LFO_MIXER_AMP, 0, MULT_2, 0);
AudioConnection          patchCord89(LFO_MIXER_AMP, 0, MULT_3, 0);
AudioConnection          patchCord90(LFO_MIXER_AMP, 0, MULT_4, 0);
AudioConnection          patchCord91(LFO_MIXER_AMP, 0, MULT_5, 0);
AudioConnection          patchCord92(LFO_MIXER_AMP, 0, MULT_6, 0);
AudioConnection          patchCord93(LFO_MIXER_AMP, 0, MULT_7, 0);
AudioConnection          patchCord94(LFO_MIXER_AMP, 0, MULT_8, 0);
AudioConnection          patchCord95(LFO_MIXER_AMP, 0, MULT_9, 0);
AudioConnection          patchCord96(LFO_MIXER_AMP, 0, MULT_10, 0);
AudioConnection          patchCord97(LFO_MIXER_AMP, 0, MULT_11, 0);
AudioConnection          patchCord98(LFO_MIXER_AMP, 0, MULT_12, 0);
AudioConnection          patchCord99(MULT_7, 0, V7_FILT, 1);
AudioConnection          patchCord100(MULT_8, 0, V8_FILT, 1);
AudioConnection          patchCord101(MULT_9, 0, V9_FILT, 1);
AudioConnection          patchCord102(MULT_10, 0, V10_FILT, 1);
AudioConnection          patchCord103(MULT_3, 0, V3_FILT, 1);
AudioConnection          patchCord104(MULT_6, 0, V6_FILT, 1);
AudioConnection          patchCord105(MULT_11, 0, V11_FILT, 1);
AudioConnection          patchCord106(MULT_5, 0, V5_FILT, 1);
AudioConnection          patchCord107(MULT_1, 0, V1_FILT, 1);
AudioConnection          patchCord108(MULT_4, 0, V4_FILT, 1);
AudioConnection          patchCord109(MULT_2, 0, V2_FILT, 1);
AudioConnection          patchCord110(MULT_12, 0, V12_FILT, 1);
AudioConnection          patchCord111(V9_FILT, 0, V9_ENV, 0);
AudioConnection          patchCord112(V7_FILT, 0, V7_ENV, 0);
AudioConnection          patchCord113(V3_FILT, 0, V3_ENV, 0);
AudioConnection          patchCord114(V2_FILT, 0, V2_ENV, 0);
AudioConnection          patchCord115(V6_FILT, 0, V6_ENV, 0);
AudioConnection          patchCord116(V8_FILT, 0, V8_ENV, 0);
AudioConnection          patchCord117(V10_FILT, 0, V10_ENV, 0);
AudioConnection          patchCord118(V1_FILT, 0, V1_ENV, 0);
AudioConnection          patchCord119(V4_FILT, 0, V4_ENV, 0);
AudioConnection          patchCord120(V5_FILT, 0, V5_ENV, 0);
AudioConnection          patchCord121(V11_FILT, 0, V11_ENV, 0);
AudioConnection          patchCord122(V12_FILT, 0, V12_ENV, 0);
AudioConnection          patchCord123(V1_ENV, 0, V14_MIX, 0);
AudioConnection          patchCord124(V2_ENV, 0, V14_MIX, 1);
AudioConnection          patchCord125(V6_ENV, 0, V58_MIX, 1);
AudioConnection          patchCord126(V7_ENV, 0, V58_MIX, 2);
AudioConnection          patchCord127(V9_ENV, 0, V912_MIX, 0);
AudioConnection          patchCord128(V3_ENV, 0, V14_MIX, 2);
AudioConnection          patchCord129(V10_ENV, 0, V912_MIX, 1);
AudioConnection          patchCord130(V5_ENV, 0, V58_MIX, 0);
AudioConnection          patchCord131(V4_ENV, 0, V14_MIX, 3);
AudioConnection          patchCord132(V8_ENV, 0, V58_MIX, 3);
AudioConnection          patchCord133(V11_ENV, 0, V912_MIX, 2);
AudioConnection          patchCord134(V12_ENV, 0, V912_MIX, 3);
AudioConnection          patchCord135(V14_MIX, 0, ALL_VOICE_MIX, 0);
AudioConnection          patchCord136(V912_MIX, 0, ALL_VOICE_MIX, 2);
AudioConnection          patchCord137(V58_MIX, 0, ALL_VOICE_MIX, 1);
AudioConnection          patchCord138(ALL_VOICE_MIX, amp1);
AudioConnection          patchCord139(amp1, 0, i2s1, 0);
AudioConnection          patchCord140(amp1, 0, i2s1, 1);
AudioControlSGTL5000     sgtl5000_1;     //xy=1390.00390625,873.9999985694885
// GUItool: end automatically generated code


#endif