// AUDIO PATCH CONNECTIONS, GENERATED BY TEENSY AUDIO DESIGN TOOL
// GUI GENERATED CODE CAN BE IMPORTED INTO TEENSY AUDIO DESIGN TOOL AND EDITED IF NECESSARY
// https://www.pjrc.com/teensy/gui/

#ifndef Audio_Connections_h
#define Audio_Connections_h


// GUItool: begin automatically generated code
AudioSynthNoiseWhite     V8_N;           //xy=572.2395629882812,1611.3333129882812
AudioSynthWaveform       V6_B;           //xy=574.2395629882812,1287.3333129882812
AudioSynthWaveform       V6_A;           //xy=575.2395629882812,1246.3333129882812
AudioSynthNoiseWhite     V7_N;           //xy=575.2395629882812,1471.3333129882812
AudioSynthWaveform       V8_B;           //xy=575.2395629882812,1568.3333129882812
AudioSynthNoiseWhite     V6_N;           //xy=576.2395629882812,1329.3333129882812
AudioSynthWaveform       V7_A;           //xy=576.2395629882812,1390.3333129882812
AudioSynthWaveform       V7_B;           //xy=577.2395629882812,1432.3333129882812
AudioSynthWaveform       V8_A;           //xy=577.2395629882812,1526.3333129882812
AudioSynthWaveform       V5_B;           //xy=580.2395629882812,1145.3333129882812
AudioSynthWaveform       V3_A;           //xy=582.2395629882812,817.3333129882812
AudioSynthWaveform       V5_A;           //xy=582.2395629882812,1105.3333129882812
AudioSynthNoiseWhite     V2_N;           //xy=584.2395629882812,770.3333129882812
AudioSynthWaveform       V3_B;           //xy=584.2395629882812,867.3333129882812
AudioSynthNoiseWhite     V3_N;           //xy=584.2395629882812,911.3333129882812
AudioSynthWaveform       V2_B;           //xy=585.2395629882812,722.3333129882812
AudioSynthNoiseWhite     V1_N;           //xy=586.2395629882812,626.3333129882812
AudioSynthWaveform       V4_A;           //xy=585.2395629882812,960.3333129882812
AudioSynthWaveform       V4_B;           //xy=585.2395629882812,1002.3333129882812
AudioSynthWaveform       V2_A;           //xy=587.2395629882812,674.3333129882812
AudioSynthNoiseWhite     V5_N;           //xy=585.2395629882812,1189.3333129882812
AudioSynthWaveform       V1_B;           //xy=590.2395629882812,587.3333129882812
AudioSynthNoiseWhite     V4_N;           //xy=591.2395629882812,1041.3333129882812
AudioSynthWaveform       V1_A;           //xy=594.2395629882812,547.3333129882812
AudioSynthWaveformDc     DC_OFFSET;      //xy=678.2395629882812,482.33331298828125
AudioMixer4              V3_MIX;         //xy=739.2395629882812,850.3333129882812
AudioMixer4              V8_MIX;         //xy=741.2395629882812,1568.3333129882812
AudioMixer4              V5_MIX;         //xy=746.2395629882812,1137.3333129882812
AudioMixer4              V7_MIX;         //xy=745.2395629882812,1425.3333129882812
AudioMixer4              V6_MIX;         //xy=747.2395629882812,1274.3333129882812
AudioMixer4              V4_MIX;         //xy=751.2395629882812,974.3333129882812
AudioMixer4              V1_MIX;         //xy=756.2395629882812,590.3333129882812
AudioMixer4              V2_MIX;         //xy=760.2395629882812,711.3333129882812
AudioSynthWaveformSine   LFO;            //xy=816.2395629882812,418.33331298828125
AudioEffectEnvelope      V7_FILT_ENV;    //xy=890.2395629882812,1395.3333129882812
AudioEffectEnvelope      V6_FILT_ENV;    //xy=896.2395629882812,1253.3333129882812
AudioEffectEnvelope      V8_FILT_ENV;    //xy=896.2395629882812,1546.3333129882812
AudioAmplifier           V8_AMP;         //xy=897.2395629882812,1594.3333129882812
AudioAmplifier           V5_AMP;         //xy=905.2395629882812,1149.3333129882812
AudioAmplifier           V7_AMP;         //xy=904.2395629882812,1432.3333129882812
AudioEffectEnvelope      V3_FILT_ENV;    //xy=909.2395629882812,833.3333129882812
AudioEffectEnvelope      V5_FILT_ENV;    //xy=910.2395629882812,1104.3333129882812
AudioAmplifier           V6_AMP;         //xy=911.2395629882812,1293.3333129882812
AudioMixer4              LFO_MIXER_FILTER; //xy=916.2395629882812,506.33331298828125
AudioAmplifier           V2_AMP;         //xy=916.2395629882812,755.3333129882812
AudioAmplifier           V4_AMP;         //xy=916.2395629882812,1006.3333129882812
AudioEffectEnvelope      V4_FILT_ENV;    //xy=917.2395629882812,965.3333129882812
AudioAmplifier           V3_AMP;         //xy=919.2395629882812,880.3333129882812
AudioAmplifier           V1_AMP;         //xy=928.2395629882812,583.3333129882812
AudioEffectEnvelope      V2_FILT_ENV;    //xy=932.2395629882812,697.3333129882812
AudioEffectEnvelope      V1_FILT_ENV;    //xy=935.2395629882812,639.3333129882812
AudioEffectMultiply      MULT_7;         //xy=1064.2395629882812,1405.3333129882812
AudioEffectMultiply      MULT_8;         //xy=1066.2395629882812,1544.3333129882812
AudioEffectMultiply      MULT_3;         //xy=1082.2395629882812,827.3333129882812
AudioEffectMultiply      MULT_6;         //xy=1083.2395629882812,1253.3333129882812
AudioEffectMultiply      MULT_5;         //xy=1089.2395629882812,1121.3333129882812
AudioEffectMultiply      MULT_1;         //xy=1093.2395629882812,578.3333129882812
AudioEffectMultiply      MULT_4;         //xy=1093.2395629882812,954.3333129882812
AudioEffectMultiply      MULT_2;         //xy=1099.2395629882812,696.3333129882812
AudioFilterStateVariable V7_FILT;        //xy=1221.2395629882812,1441.3333129882812
AudioFilterStateVariable V3_FILT;        //xy=1224.2395629882812,867.3333129882812
AudioFilterStateVariable V2_FILT;        //xy=1226.2395629882812,753.3333129882812
AudioFilterStateVariable V6_FILT;        //xy=1225.2395629882812,1292.3333129882812
AudioFilterStateVariable V8_FILT;        //xy=1225.2395629882812,1577.3333129882812
AudioFilterStateVariable V1_FILT;        //xy=1248.2395629882812,641.3333129882812
AudioFilterStateVariable V4_FILT;        //xy=1247.2395629882812,986.3333129882812
AudioFilterStateVariable V5_FILT;        //xy=1249.2395629882812,1140.3333129882812
AudioEffectEnvelope      V1_ENV;         //xy=1411.2395629882812,657.3333129882812
AudioEffectEnvelope      V2_ENV;         //xy=1418.2395629882812,744.3333129882812
AudioEffectEnvelope      V6_ENV;         //xy=1427.2395629882812,1236.3333129882812
AudioEffectEnvelope      V7_ENV;         //xy=1430.2395629882812,1299.3333129882812
AudioEffectEnvelope      V3_ENV;         //xy=1433.2395629882812,868.3333129882812
AudioEffectEnvelope      V5_ENV;         //xy=1441.2395629882812,1149.3333129882812
AudioEffectEnvelope      V4_ENV;         //xy=1445.2395629882812,993.3333129882812
AudioEffectEnvelope      V8_ENV;         //xy=1446.2395629882812,1441.3333129882812
AudioMixer4              V14_MIX;        //xy=1743.2395629882812,1006.3333129882812
AudioMixer4              V58_MIX;        //xy=1744.2395629882812,1076.3333129882812
AudioMixer4              ALL_VOICE_MIX;  //xy=1923.2395629882812,1048.3333129882812
AudioMixer4              LFO_MIXER_AMP;  //xy=2116.239570617676,886.0000190734863
AudioEffectMultiply      LFO_AMP;        //xy=2120.2395629882812,1037.3333129882812
AudioAmplifier           MASTER_GAIN;    //xy=2230.239875793457,1134.9999160766602
AudioOutputI2S           i2s1;           //xy=2364.2395629882812,1055.3333129882812
AudioAnalyzePeak         PEAK;          //xy=2412.239814758301,1240.5729970932007
AudioConnection          patchCord1(V8_N, 0, V8_MIX, 2);
AudioConnection          patchCord2(V6_B, 0, V6_MIX, 1);
AudioConnection          patchCord3(V6_A, 0, V6_MIX, 0);
AudioConnection          patchCord4(V7_N, 0, V7_MIX, 2);
AudioConnection          patchCord5(V8_B, 0, V8_MIX, 1);
AudioConnection          patchCord6(V6_N, 0, V6_MIX, 2);
AudioConnection          patchCord7(V7_A, 0, V7_MIX, 0);
AudioConnection          patchCord8(V7_B, 0, V7_MIX, 1);
AudioConnection          patchCord9(V8_A, 0, V8_MIX, 0);
AudioConnection          patchCord10(V5_B, 0, V5_MIX, 1);
AudioConnection          patchCord11(V3_A, 0, V3_MIX, 0);
AudioConnection          patchCord12(V5_A, 0, V5_MIX, 0);
AudioConnection          patchCord13(V2_N, 0, V2_MIX, 2);
AudioConnection          patchCord14(V3_B, 0, V3_MIX, 1);
AudioConnection          patchCord15(V3_N, 0, V3_MIX, 2);
AudioConnection          patchCord16(V2_B, 0, V2_MIX, 1);
AudioConnection          patchCord17(V1_N, 0, V1_MIX, 2);
AudioConnection          patchCord18(V4_A, 0, V4_MIX, 0);
AudioConnection          patchCord19(V4_B, 0, V4_MIX, 1);
AudioConnection          patchCord20(V2_A, 0, V2_MIX, 0);
AudioConnection          patchCord21(V5_N, 0, V5_MIX, 2);
AudioConnection          patchCord22(V1_B, 0, V1_MIX, 1);
AudioConnection          patchCord23(V4_N, 0, V4_MIX, 2);
AudioConnection          patchCord24(V1_A, 0, V1_MIX, 0);
AudioConnection          patchCord25(DC_OFFSET, V1_FILT_ENV);
AudioConnection          patchCord26(DC_OFFSET, V2_FILT_ENV);
AudioConnection          patchCord27(DC_OFFSET, V3_FILT_ENV);
AudioConnection          patchCord28(DC_OFFSET, V4_FILT_ENV);
AudioConnection          patchCord29(DC_OFFSET, V5_FILT_ENV);
AudioConnection          patchCord30(DC_OFFSET, V6_FILT_ENV);
AudioConnection          patchCord31(DC_OFFSET, V7_FILT_ENV);
AudioConnection          patchCord32(DC_OFFSET, V8_FILT_ENV);
AudioConnection          patchCord33(DC_OFFSET, 0, LFO_MIXER_FILTER, 0);
AudioConnection          patchCord34(DC_OFFSET, 0, LFO_MIXER_AMP, 0);
AudioConnection          patchCord35(V3_MIX, V3_AMP);
AudioConnection          patchCord36(V8_MIX, V8_AMP);
AudioConnection          patchCord37(V5_MIX, V5_AMP);
AudioConnection          patchCord38(V7_MIX, V7_AMP);
AudioConnection          patchCord39(V6_MIX, V6_AMP);
AudioConnection          patchCord40(V4_MIX, V4_AMP);
AudioConnection          patchCord41(V1_MIX, V1_AMP);
AudioConnection          patchCord42(V2_MIX, V2_AMP);
AudioConnection          patchCord43(LFO, 0, LFO_MIXER_FILTER, 1);
AudioConnection          patchCord44(LFO, 0, LFO_MIXER_AMP, 1);
AudioConnection          patchCord45(V7_FILT_ENV, 0, MULT_7, 1);
AudioConnection          patchCord46(V6_FILT_ENV, 0, MULT_6, 1);
AudioConnection          patchCord47(V8_FILT_ENV, 0, MULT_8, 1);
AudioConnection          patchCord48(V8_AMP, 0, V8_FILT, 0);
AudioConnection          patchCord49(V5_AMP, 0, V5_FILT, 0);
AudioConnection          patchCord50(V7_AMP, 0, V7_FILT, 0);
AudioConnection          patchCord51(V3_FILT_ENV, 0, MULT_3, 1);
AudioConnection          patchCord52(V5_FILT_ENV, 0, MULT_5, 1);
AudioConnection          patchCord53(V6_AMP, 0, V6_FILT, 0);
AudioConnection          patchCord54(LFO_MIXER_FILTER, 0, MULT_1, 0);
AudioConnection          patchCord55(LFO_MIXER_FILTER, 0, MULT_2, 0);
AudioConnection          patchCord56(LFO_MIXER_FILTER, 0, MULT_3, 0);
AudioConnection          patchCord57(LFO_MIXER_FILTER, 0, MULT_4, 0);
AudioConnection          patchCord58(LFO_MIXER_FILTER, 0, MULT_5, 0);
AudioConnection          patchCord59(LFO_MIXER_FILTER, 0, MULT_6, 0);
AudioConnection          patchCord60(LFO_MIXER_FILTER, 0, MULT_7, 0);
AudioConnection          patchCord61(LFO_MIXER_FILTER, 0, MULT_8, 0);
AudioConnection          patchCord62(V2_AMP, 0, V2_FILT, 0);
AudioConnection          patchCord63(V4_AMP, 0, V4_FILT, 0);
AudioConnection          patchCord64(V4_FILT_ENV, 0, MULT_4, 1);
AudioConnection          patchCord65(V3_AMP, 0, V3_FILT, 0);
AudioConnection          patchCord66(V1_AMP, 0, V1_FILT, 0);
AudioConnection          patchCord67(V2_FILT_ENV, 0, MULT_2, 1);
AudioConnection          patchCord68(V1_FILT_ENV, 0, MULT_1, 1);
AudioConnection          patchCord69(MULT_7, 0, V7_FILT, 1);
AudioConnection          patchCord70(MULT_8, 0, V8_FILT, 1);
AudioConnection          patchCord71(MULT_3, 0, V3_FILT, 1);
AudioConnection          patchCord72(MULT_6, 0, V6_FILT, 1);
AudioConnection          patchCord73(MULT_5, 0, V5_FILT, 1);
AudioConnection          patchCord74(MULT_1, 0, V1_FILT, 1);
AudioConnection          patchCord75(MULT_4, 0, V4_FILT, 1);
AudioConnection          patchCord76(MULT_2, 0, V2_FILT, 1);
AudioConnection          patchCord77(V7_FILT, 0, V7_ENV, 0);
AudioConnection          patchCord78(V3_FILT, 0, V3_ENV, 0);
AudioConnection          patchCord79(V2_FILT, 0, V2_ENV, 0);
AudioConnection          patchCord80(V6_FILT, 0, V6_ENV, 0);
AudioConnection          patchCord81(V8_FILT, 0, V8_ENV, 0);
AudioConnection          patchCord82(V1_FILT, 0, V1_ENV, 0);
AudioConnection          patchCord83(V4_FILT, 0, V4_ENV, 0);
AudioConnection          patchCord84(V5_FILT, 0, V5_ENV, 0);
AudioConnection          patchCord85(V1_ENV, 0, V14_MIX, 0);
AudioConnection          patchCord86(V2_ENV, 0, V14_MIX, 1);
AudioConnection          patchCord87(V6_ENV, 0, V58_MIX, 1);
AudioConnection          patchCord88(V7_ENV, 0, V58_MIX, 2);
AudioConnection          patchCord89(V3_ENV, 0, V14_MIX, 2);
AudioConnection          patchCord90(V5_ENV, 0, V58_MIX, 0);
AudioConnection          patchCord91(V4_ENV, 0, V14_MIX, 3);
AudioConnection          patchCord92(V8_ENV, 0, V58_MIX, 3);
AudioConnection          patchCord93(V14_MIX, 0, ALL_VOICE_MIX, 0);
AudioConnection          patchCord94(V58_MIX, 0, ALL_VOICE_MIX, 1);
AudioConnection          patchCord95(ALL_VOICE_MIX, 0, LFO_AMP, 1);
AudioConnection          patchCord96(LFO_MIXER_AMP, 0, LFO_AMP, 0);
AudioConnection          patchCord97(LFO_AMP, MASTER_GAIN);
AudioConnection          patchCord98(MASTER_GAIN, 0, i2s1, 0);
AudioConnection          patchCord99(MASTER_GAIN, 0, i2s1, 1);
AudioConnection          patchCord100(MASTER_GAIN, PEAK);
AudioControlSGTL5000     sgtl5000_1;     //xy=1841.2395629882812,1263.3333129882812
// GUItool: end automatically generated code



#endif